### ISSUE TITLE
Interest of the sample "test" in your dataset of test

### ISSUE THREAD

**Issue by emlec** [a-slide/FastqFT#3]
Hi Adrien, 

What is the interest of the sample "test" to test the installation/modification of Sekator. The sample "S1" is not sufficient? I would like to send you a pull request with an update of the folder /test/result without the sample "test".

**Comment by a-slide** [comment]
Hi Emilie,
test*.fatsq  are small files containing a few artificial sequences for which you can expect a specific output.
For example the "@Qual_30" sequence has a mean quality of 30, "@Adapt_start_1_30b" contain an adaptor sequence of 30pb at its end ...
I used the files to run tests when developing the package. I would suggest not removing it, as it could be useful for further development. I don't have any plan to carry on at the moment, but I will eventually, convert it to python3 and write it as a pip package one day. Please go ahead and fork it if you want to develop it further.

Cheers
Ad
